name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  cache_key:
    description: 'Cache Key to Delete'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
